### ISSUE TITLE
Replace all the GNN layer ops kernels with the corresponding APIs from cugraph-ops

### ISSUE THREAD

**Issue by teju85** [rapidsai/wholegraph#17]
All (if not most) of the GNN layer ops in cugraph-ops should already help do the job, for which we have specific kernels in WholeGraph. Thus, there's lot of duplication of code between these 2 projects. We must further refactor WG GNN layer ops in order to use the ones from cugraph-ops instead of having to maintain specific kernels for these in WG.

1. If not attempted already, please prepare a plan to replace these kernels with the corresponding calls from cugraph-ops in the next release cycle?
2. If attempted, can you file issues against cugraphops for any missing features that are preventing this from happening?

**Comment by dongxuy04** [comment]
@teju85 Have replaced GNN layer related ops with cugraph-ops from python level. Could you help check that and maybe we can close this issue? Thanks!
