### ISSUE TITLE
Is there any other way to install wholegraph if not using docker in branch-23.06?

### ISSUE THREAD

**Issue by Aftermath863** [rapidsai/wholegraph#59]
Is there any other way to install wholegraph if not using docker in branch-23.06?

**Comment by dongxuy04** [comment]
For 23.06, it is recommended to use Dockerfile. If you want to setup your environment by yourself, you may refer to the Dockerfile to setup related environments.
Some version requirements for dependencies:

- gcc / g++ >= 9
- cmake >= 3.23.1
- pybind11 == 2.4.3 (wget https://github.com/pybind/pybind11/archive/refs/tags/v2.4.3.zip && unzip v2.4.3.zip && cd pybind11-2.4.3 && mkdir build && cd build && update-alternatives --set python /usr/local/bin/python3 && cmake ../ && make -j && make install)
